### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by narodejesus** [pcofilada/react-native-boilerplate#2]
I like the idea of having a simple react native boilerplate but it seems that there are some points that are lacking in this code/code structure that may introduce bottlenecks for beginners (opinion btw). 

I took notice of this repository since i am looking for a boilerplate that I can use for my simple app.. well you posted this on facebook 👍 

but really Great Work! and a good move since there are a lot of repositories out there that has introduced complexity for beginners 👍 .. If you want I can send a PR to improve this code so I can point it out directly. OR just message me on facebook

**Comment by pcofilada** [comment]
@narodejesus Thank you for taking time to look on this project. Yup just send your PR so we can improve this boilerplate and beginners could use it without any problem.

**Comment by nomoreboredom** [comment]
I second to @narodejesus, this is the best stack currently, especially after react navigation!

**Comment by narodejesus** [comment]
Im planning to use this project.. 
and add some good existing library to easily manage state and action creators 👍
